### ISSUE TITLE
Registration form error messages

### ISSUE THREAD

**Issue by bakermanus** [OmarElGabry/miniPHP#10]
Hi,
First of all i'd like to say thank you for your work and your generosity to make this code public and free.
I have just installed it on my localhost and i have tried the demo accounts and everything works as they should. However, when i tried to create new account there is no error message displayed only empty registration form. When everything ok with the registration then you get successful message but when error occurs you can't see what the error is.
It might be just on my system because nobody has come up with this issue yet.
My system mac 10.11.4  mamp php 5.6
Would you please help me to resolve this issue?
Thanks

**Comment by ghost** [comment]
Without error information anybody can't help you..

**Comment by bakermanus** [comment]
Hi,
I don't get form errors. That's the issue.  For example when username taken it will not register or display error.
So basically you don't know why registration was not successful.
Thanks

**Comment by Everterstraat** [comment]
You did have disabled any logging in php.ini? You can send me a mail on evert@achterstraat.com but be fast, will remove my mail address within 5 minutes.

**Comment by bakermanus** [comment]
Look it has nothing to do with php error.  When you process registration and for example username taken, in normal case the error would be shown "This username has been taken" Right?
This is what i don't get  From the controller there is a function that is called from the model.
$this->login->errors()
Which should return with the error message, but it returns empty.
Even tho in the model there is a error set
 $this->errors = $validation->errors();
i tried 
die(print_r($this->errors))  in the model and i had the errors fine however when it's called from the controller it returns empty, therefor there is no error displayed on the registration form.

**Comment by ghost** [comment]
>  in the model and i had the errors fine
> What do you mean with errors fine? Errors or no errors?

It can be a mysql issue, you can mostly also find it back in the php log but is depends on how you've configured the local installation.

Of isn't a issue at all and do you actually request a future?

**Comment by bakermanus** [comment]
It is not a feature request.

 here is a pice of code from login model
`
if(!$validation->validate([
            "User Name" => [$name, "required|alphaNumWithSpaces|minLen(4)|maxLen(30)"],
            "Email" => [$email, "required|email|emailUnique|maxLen(50)"],
            'Password' => [$password, "required|equals(".$confirmPassword.")|minLen(6)|password"],
            'Password Confirmation' => [$confirmPassword, 'required']])) {

```
        $this->errors = $validation->errors();
        $isValid = false;
    }
```

`

This is where form validation happens. If error occurs  then the error message is stored in $this->errors .

Which is working within  the registration function in login model but it returns empty in the controller.

**Comment by ghost** [comment]
Do you've a demo url?

**Comment by bakermanus** [comment]
Never mind. Thanks for your help.

**Comment by OmarElgabry** [comment]
@bakermanus You are right!. This is because the last commit. It's fixed now.
Thanks.

**Comment by bakermanus** [comment]
Thanks Omar. I found the issue after a while. Great work anyway
