### ISSUE TITLE
PDO::prepare should return $this not void, for several execute before commit. 

### ISSUE THREAD

**Issue by Creeall** [OmarElGabry/miniPHP#13]
I hate to post issues, when in fact it's a request. But pull request look a hell of work for this.

Currently your Database class extending PDO state that prepare don't return anything.
I had to prepare several include in several tables and be sure to cancel all these insert if at least one failed. It's usually done by commit/rollback. But to do this you have to store each action in several variables like so :  Way easier to organize and readable.

```
$database->openConnection();
$database->begintransaction();

$action1 = $database->prepare("STUFF");
$action1->bindValue(:stuff, stuff);
$action1->execute();

$action2 = $satabase->prepare("OTHER STUFF");
$action2->bindValue(:stuff, stuff);
$action2->execute();

if(all good){
$database->commit();
} else {
$database->rollback()
}

```

What do you think ?
I just add (return $this) in Database prepare method and we good.

**Comment by OmarElgabry** [comment]
I would do something like this instead:

``` php
$database = Database::openConnection();
$database->beginTransaction();

$actions = [
     ['query' => 'INSERT INTO TABLE1', 'values' => $values], 
     [...],
]

for($action in $actions){
  $database->prepare($action['query']);
  $result = $database->execute($action['values']);

  if(!$result){
        $database->rollBack();
        throw new Exception("Couldn't Insert");
   }
}

$database->commit();
```

**Comment by Creeall** [comment]
Makes sens too yeah. Still don't get why one would be better thought. Can you explain this please ?
Btw isn't native behavior of PDO to return the object on prepare ?
How would you use the $options array to build each queries only if param's value is given ? (use of ->applyOptions() ?

**Comment by OmarElgabry** [comment]
> Still don't get why one would be better thought.

I am sorry, I don't understand what do you exactly mean.

> Btw isn't native behavior of PDO to return the object on prepare ?

`Database::prepare()` in miniPHP has nothing to do with `PDO::prepare()`. Yes, It uses the `PDO::prepare()` method, which in turn prepares a SQL query for execution, and returns a `PDOStatement` object.

> How would you use the $options array to build each queries only if param's value is given ? (use of ->applyOptions() ?

Check these [lines of code](https://github.com/OmarElGabry/miniPHP/blob/e45244df3530c5a7ec646972b6f7efd52fffe03f/app/models/Admin.php#L38).  _Kindly note that when using PDO::execute(), All values are treated as PDO::PARAM_STR._
