### ISSUE TITLE
Triggers

### ISSUE THREAD

**Issue by ghost** [OmarElGabry/miniPHP#14]
For each trigger there also has to be a increment on update or at least a decrement after deleted!

After insert;

```
DROP TRIGGER IF EXISTS `increment_notifications_post_inserted`;
DELIMITER //
CREATE TRIGGER `increment_notifications_post_inserted` AFTER INSERT ON `posts`
 FOR EACH ROW UPDATE notifications SET count = count+1 
WHERE notifications.user_id != NEW.user_id 
AND   notifications.target = "posts"
//
DELIMITER ;
```

After update;

```
DROP TRIGGER IF EXISTS `increment_notifications_post_updated`;
DELIMITER //
CREATE TRIGGER `increment_notifications_post_updated` AFTER UPDATE ON `posts`
 FOR EACH ROW UPDATE notifications SET count = count+1 
WHERE notifications.user_id != NEW.user_id 
AND   notifications.target = "posts"
//
DELIMITER ;
```

After delete;

```
DROP TRIGGER IF EXISTS `decrement_notification_post_deleted`;
DELIMITER //
CREATE TRIGGER `decrement_notification_post_deleted` AFTER DELETE ON `posts`
 FOR EACH ROW UPDATE notifications SET count = count-1 
WHERE notifications.user_id != OLD.user_id 
AND   notifications.target = "posts"
//
DELIMITER ;
```

**Comment by OmarElgabry** [comment]
You are right. But, the solution you suggested won't be correct. For example, assume that a user hasn't seen 5 new notifications; 5 newly created posts. Now, what if the owner deleted a post, but, this post wasn't one of the newly created ones? The `count`will be decremented too, which shouldn't be. 

So, I left this issue to keep it simple. Hopefully someone will find a simple solution later.

**Comment by ghost** [comment]
You're also right @OmarElGabry. A solution can be to add separate notifications and notification_updates with a row for each user that have seen a notification but with a lot of users it  generates a lot unnecessary data.
So the way it's designed i'll leave it for now, maybe in a later stadium i'll write above described solution.
