### ISSUE TITLE
Not compatible with IIS or Azure

### ISSUE THREAD

**Issue by just-cmm503** [OmarElGabry/miniPHP#22]
Routing to public/ affects the complete frame work under IIS or Azure, you can only get login page.

**Comment by OmarElgabry** [comment]
I am not aware actually with using IIS or Azure. So, I won't be able to help much. But, I am sure you will find your way around it.

**Comment by t3kn04r33k** [comment]
I think I had similar issues with getting tis up and running on my setup on Linux. This is what i did to make things work on my setup. This might help others. 

1. Locate public/index.php and add the following items to your file.


// Config::set('base', str_replace("\\", "/", dirname(__DIR__)));
// Config::set('images', str_replace("\\", "/", __DIR__) . "/img/");
// Config::set('app', Config::get('base') . "/app/");

'+ /**'
'+ * @def (string) DS - Directory separator.'
'+ */'
'+ define("DS","/",true);'

define('BASE_DIR', str_replace("\\", "/", dirname(__DIR__)));
......

$app = new App();

// Config::set('root', $app->request->root());
' - define('PUBLIC_ROOT', $app->request->root()); '
' + define('PUBLIC_ROOT', $app->request->root().DS); '

2. Locate the .htaccess file under the public folder

RewriteEngine On
' + RewriteBase /miniPHP  #add a rewritebase option if not '
RewriteCond %{REQUEST_FILENAME} !-d
