### ISSUE TITLE
Not able to login

### ISSUE THREAD

**Issue by nk932714** [OmarElGabry/miniPHP#29]
admin@demo.com      password = 12345
user@demo.com     password = 12345

both above demo ID's are not working

**Comment by nk932714** [comment]
both above ID are given in your readme.md github file

**Comment by ghost** [comment]
On the [demo](https://miniphp.ga) you can login with admin@miniphp.ga or user@miniphp.ga

On the local installation you can login with admin@demo.com and user@demo.com after you've run this [sql](https://github.com/OmarElGabry/miniPHP/blob/master/_installation/04%20users.sql) file!

I both situations the passwords are 12345

**Comment by nk932714** [comment]
Thanks a lot buddy...
