### ISSUE TITLE
php7

### ISSUE THREAD

**Issue by Chriscxa** [OmarElGabry/miniPHP#5]
anyone tested in php7?

**Comment by ghost** [comment]
Yes, can confirm it works on PHP7 RC 3.

**Comment by Chriscxa** [comment]
cool. Thanx. great work

**Comment by Chriscxa** [comment]
# in php7.04:

Fatal error: Uncaught Error: Call to undefined method Error::register() in F:\xampp704\htdocs\miniPHP-master\public\index.php:7 Stack trace: #0 {main} thrown in F:\xampp704\htdocs\miniPHP-master\public\index.php on line 7

**Comment by ghost** [comment]
Thats right, changes to Errors::register cause Error is a predefined class in PHP7.

So, without that little workaround it doesn't work yet in PHP7!

**Comment by Chriscxa** [comment]
ah ok. found it: http://php.net/manual/en/class.error.php
Only a little issue. thx

**Comment by ghost** [comment]
Sooo little that i've forgotten, excuse me! :)

**Comment by OmarElgabry** [comment]
You are right, I'll fix it in the later version, till now you can change it to _Errors_ instead of _Error_  as @Everterstraat suggested.

Thanks
